// ---------------------------------------------------------------------------
// In-game help: "How it works".
//
// Open with the "?" button (after Goals) or F1; Esc or Close shuts it.
// Topics down the left, text on the right. To add or change a topic, edit
// HELP_TOPICS: each has a title and a list of lines ("" = gap, lines
// starting with "# " are small headings, "- " are bullets).
// ---------------------------------------------------------------------------

const HELP_TOPICS = [
  {
    title: "Getting started",
    lines: [
      "You run a fluffy breeding business: raise fluffies, breed them for",
      "good colours and rare types, and sell them or fill customer orders.",
      "",
      "# Saving",
      "- The game saves itself every morning, every few minutes, and",
      "  whenever you switch away from it (\"Autosave\"; the one before is",
      "  kept as \"Autosave (earlier)\"). Continue on the title screen",
      "  picks up from your last save. Save/Load in the menu still works.",
      "- On a website (or added to a phone's home screen) it keeps",
      "  working with no internet after the first time.",
      "",
      "# Money",
      "- Buyers knock at the door, each after something different.",
      "- Selling one yourself (shift + click, or the sell cage) pays half.",
      "- Now and then a biology teacher comes for a body, or a fluffy",
      "  that's dying, for a class. He takes it away.",
      "- Keep (by the price in the magnifying glass, or Not for sale in its",
      "  menu): buyers pass it by and you can't sell it by accident.",
      "- Customer orders (bounty board on Shopping Street, or the Computer)",
      "  pay the most, and raise your reputation.",
      "- Goals (the Goals button, or G) pay a reward once each.",
      "- Rent and bills come out every morning (see Money trouble).",
      "",
      "# Looking after them",
      "- Keep bowls full (kibble from Fluff Mart, down from the garden, or",
      "  ordered on the Computer's Food tab: in your shopping bag 2 hours",
      "  later; $5 delivery, free over $100).",
      "- Setting one of yours down outside puts it out (you're asked):",
      "  it's a stray that misses you. Right-click at home: Put out.",
      "- Strays that get into the backyard aren't yours: you're asked",
      "  whether to keep them or shoo them out.",
      "- The Lawn Mower (Fluff Mart): sweep it over long grass outside.",
      "- Shopping: small things (food, bowls, toys, hats) go in your",
      "  shopping bag - the tan buttons in the toolbox. Click one to take",
      "  it out and click to put it down. Carry something small onto the",
      "  toolbox to pack it away. Big things (cages, troughs, beds, fences,",
      "  the TV...) are delivered: they're waiting in your living room.",
      "- Shift-click a bag button (long-press on a phone) to take out all",
      "  of that kind: put the first down and the rest go beside it.",
      "- Big things are delivered to the room the \"Deliver to\" button",
      "  says (in Fluff Mart's aisles, and on the computer): click it to",
      "  pick another room or the backyard.",
      "- The Computer's Items tab: order cages, toys, beds and the rest,",
      "  delivered in about 2 hours ($5, free from $100).",
      "- The scoop (in your toolbox): drag a box round fluffies to pick",
      "  them all up at once - a litter out of a cage, say - and click to",
      "  set them all down. Over a cage, they go in it.",
      "- \u{1F6E0} Fit out (next to a room's name): pay once to set a room up",
      "  as a mill, family room, nursery or clinic - everything for it,",
      "  laid out (10% less than buying it all). The mill nearly runs",
      "  itself: eight cages, a Feed-Bot, a Fluff-Bot and Auto-Trainers.",
      "- The Mop (Care & Cleaning): cleans a wide patch of mess at once and",
      "  never bathes anyone.",
      "- Diapers (Care & Cleaning): click a fluffy of yours to put one on.",
      "  No mess on the floor, but it waddles about unhappy - right-click:",
      "  Change diaper (or it leaks when it's full).",
      "- Wet after a bath, the sprinkler or rain: the cold bites harder.",
      "  Right-click: Dry it - towel, hair dryer (loud) or peg it up.",
      "- The magnifying glass shows everything about a fluffy.",
      "- Right-click one of yours for tricks, lessons, care and more - or",
      "  Actions in its magnifying glass (the same menu).",
      "- The menu (Esc) has switches for names, herd markers and bed names",
      "  (or N, H and B).",
      "- The family tree and Gene Lab help you plan litters. Breeding",
      "  records (Records button, or L) show every litter you've bred,",
      "  what each foal sold for, and which parents earn the most.",
      "",
      "# Today (button at the top, or T)",
      "- Urgent (red): money owed, the inspector's visit, a fluffy starving,",
      "  frightened, bleeding or ill, one close to breaking, a Rebel.",
      "- Chances (gold): a wish you could grant, a reason for a party, a",
      "  title about to change, a sad fluffy you could sit with.",
      "- The house (blue): rooms that feel tense, fearful or grieving,",
      "  crowded rooms, the Feed-Bot, anniversaries.",
      "- The badge counts what's urgent (or the chances). Click a row to",
      "  go to that fluffy.",
      "",
      "# Household (button at the top, or O)",
      "- Every fluffy you own, its room, hearts and what it needs - click",
      "  one to go to it. Your name with families and with the dark market",
      "  is at the top; the Memories book button is at the bottom.",
      "",
      "# Who's who (Relationships in Household, or M)",
      "- A map of your fluffies: herds and families in rings, with lines",
      "  for love (green), family (grey), grudges and fights (red), fear",
      "  (purple) and gossip about you (gold, from teller to listener).",
      "  An arrow means one way only. Switch kinds on and off at the top;",
      "  You adds a line from each fluffy that trusts or fears you.",
      "- Hover a fluffy to light up its lines; click it for the details,",
      "  and Show me to go to it. All its ties lists everyone it has",
      "  family, friendship or a grudge with - here, in the wild, sold or",
      "  gone - and the herds it has been in.",
      "",
      "# Hints",
      "- The first time something new happens, a hint card pops up at the",
      "  top right; Read more opens the page about it here. Switch them",
      "  off with the Hints button (top right of this screen).",
    ],
  },
  {
    title: "Food, play & cleaning",
    lines: [
      "What fluffies need day to day, besides you.",
      "",
      "# Food and diet",
      "- Kibble brands: Fluffy Feast Premium ($80, very nutritious, loved),",
      "  Kibble ($25, some like it, some don't), Value Kibble ($10, bland,",
      "  they're hungry again sooner), Scrapz ($3, made from ground-up",
      "  fluffies - the grinder makes it too. Most refuse it until starving,",
      "  and it hurts them and upsets their tummies).",
      "- Sketties ($120): their favourite junk food. Happy, but fattening.",
      "- Each fluffy has its own tastes and a favourite food (magnifying",
      "  glass). Picky eaters are fussier; greedy ones eat anything.",
      "- Diet (what it's been eating lately): good food means shinier coats",
      "  at shows, higher prices, faster-growing foals, better pregnancies",
      "  and slow healing. Poor food, the opposite.",
      "- Sketties and training treats make them chubby, then fat: slower,",
      "  worse at shows, and it's bad for their health. It burns off.",
      "",
      "# The Feed-Bot",
      "- Fluff Mart, $300. Hold a food bag over it to pour it in (formula",
      "  goes in its own tank). It fills the bowls in its room (in cages",
      "  too, through the bars), keeps baby feeders topped up and feeds",
      "  orphaned newborns (and ones their mum turns away, or that are",
      "  going hungry). Litterboxes are the Fluff-Bot's job.",
      "- Right-click to change mode: Keep full, Mealtimes (fills bowls at",
      "  breakfast and dinner and rings a bell - fluffies learn to come",
      "  running), Small portions (half bowls, for fat fluffies), Off.",
      "- Its meals aren't you feeding them: no affection from them.",
      "- Rowdy fluffies sometimes knock it over. Pick it up or right-click",
      "  to stand it up. If it breaks: a Repair Kit ($40), or right-click",
      "  to send it for repair ($80, back tomorrow).",
      "",
      "# Play and boredom",
      "- Fluffies get bored with nothing to do (faster if playful). Balls,",
      "  blocks, the TV, tricks and the park all help; each has a favourite toy.",
      "- Play with them: pick up a ball and wave it near them - they chase it.",
      "  Great for boredom and affection, and it burns off sketties.",
      "- Very bored fluffies get unhappy and cause trouble: knocking over",
      "  food bowls and picking on others.",
      "",
      "# The throw tool",
      "- Always first in your toolbox. Click a fluffy with it to lift it,",
      "  then let go: it drops, or flies off as fast as you were moving.",
      "  A hard landing hurts (it can kill), and it remembers who threw it.",
      "  Pegasi with both wings love it.",
      "- A pegasus (or alicorn) with both wings can't really fly, but it",
      "  flaps as it falls: it lands softer and survives falls that would",
      "  hurt another fluffy. Each throw makes its wings a little stronger;",
      "  strong wings land it on its feet from a small fall.",
      "- Or the gentle way: a Wing perch ($90, Toys & Gadgets). Pegasi go over",
      "  by themselves to hop and flutter - slower, but fun and nothing to",
      "  fear.",
      "- A hard throw can do lasting harm: a mangled leg (it limps, slower",
      "  for good), a mangled wing (it can't flap any more) or a snapped",
      "  horn. The harder the throw, the likelier. It never heals, and it",
      "  sells for less.",
      "",
      "# Surgery (knife and scalpel)",
      "- Click a fluffy with either to open a chart of it: Front, Side",
      "  (flip for the other side), Back and Underside. Hover over a part",
      "  to light it up; click it (or its name in the list) and say yes.",
      "- Knife: it bleeds and hurts - stitch it with the suture kit, or",
      "  burn it shut with the cautery iron ($120, never runs out): agony,",
      "  no thanks for it, and a burn scar for life. Both are buttons on",
      "  the surgery chart while it bleeds, or click it with the tool.",
      "  Scalpel: a clean cut. Spay or neuter from the Underside view.",
      "- An operating table set to a part marks it as planned.",
      "- Surgery jobs: with an operating table, customers sometimes ask",
      "  you to neuter, spay, dock a tail or take off a mangled leg. Their",
      "  fluffy is dropped off; do it by the end of the next day. Paid by",
      "  how well it comes through - cut anything else and your name",
      "  suffers.",
      "- Afterwards it recovers for half a day, and the wound can get",
      "  infected (a fever that can kill; the vet cures it). Likelier with",
      "  the knife, and away from an operating table. Stitching halves the",
      "  risk, burning it shut ends it, and resting (asleep, lying down, in",
      "  bed) helps; a filthy fluffy is likelier to catch it.",
      "- Bandages ($30, 6 wraps): once it's stopped bleeding, wrap the",
      "  wound - half as likely to go bad. Recovering fluffies move slower;",
      "  knocks while healing (a fight, a hard landing) set them back.",
      "",
      "# Cage modes",
      "- Right-click (or long-press) a plain cage to change its mode: none,",
      "  breeding, sell, eject and cull. Put fluffies in first, then:",
      "  eject - tap the cage and everything drops out; cull - tap the",
      "  cage and say yes: the glass seals and everything inside",
      "  suffocates. (An empty cage just picks up as usual.)",
      "- Breeding: put a stallion and a mare in, then hit him with the",
      "  sorry stick, spray or tack. If it won't work (she's pregnant or",
      "  resting after a litter, he needs a rest...) you're told why, and",
      "  he isn't hit. After about four times he's a trained stud: in a",
      "  breeding cage with a mare he breeds by himself.",
      "- Fluffies that know what a cage is for react when put in one: one",
      "  that's seen a cull panics in the cull cage, one that's seen",
      "  others sold begs to stay. Behind bars they can still talk to",
      "  friends and family outside (who come over to the bars), but",
      "  can't touch, play or come to parties - and they mind missing one.",
      "- Set a cage down beside another and it snaps flush, level with it.",
      "- An accident in a cage stays in the cage: it's upset, and everyone",
      "  in there gets sadder and dirtier until you sponge it (or the",
      "  sprinkler washes it). A litterbox in the cage: they learn to use it.",
      "- Weaning tags: right-click a weaned foal - breeder, pet or feed (a",
      "  test suggests one). Sets its price; the reptile shop wants feed.",
      "- Milk stand ($350, Hardware): strap a grown mare on - any foal in",
      "  the room drinks from her, she can't refuse. Fill its trough",
      "  (right-click). She hates it.",
      "- Incubator ($350, Pharmacy & Lab): for foals still on milk, two at",
      "  a time. Warm and tube-fed, and a frail early foal gets stronger",
      "  twice as fast. No power, no warmth.",
      "",
      "# Dirt and bath time",
      "- Fluffies get grubby: standing in mess, going on the floor, rain",
      "  outside, and slowly anyway. Dirty ones look browner; filthy ones",
      "  smell (flies!), are unhappy, score less at shows and sell for less.",
      "- Bath time: scrub the sponge back and forth on a fluffy (sweeping",
      "  it past one doesn't count). Some love it, some scream - but every",
      "  bath gets them a bit more used to it.",
      "- Mess fades by itself: pee in a few hours, poop within a day",
      "  (twice as fast outside). Rain washes the garden, backyard and park",
      "  clean in about a minute. Blood indoors needs the sponge.",
      "- The Fluff-Bot (Fluff Mart, $250) cleans up the floor of the room",
      "  you put it in by itself, and empties its litterboxes once they're",
      "  a quarter full. Right-click to switch it off.",
      "- A pet flap (Fluff Mart, $200) in a room of the house lets your",
      "  fluffies go out to the backyard and back on their own (not at",
      "  night or in bad weather). Right-click to lock it: unlocked, strays",
      "  and raiders in the yard can get in too.",
      "- Litter training (a lesson) means fewer messes, and adds to the price.",
      "  Picking a foal up and setting it down in the litterbox teaches it",
      "  too (once an hour; best when it needs to go).",
      "",
      "# Coats",
      "- Some fluffies have long coats (it runs in families). Warmer in the",
      "  cold, hotter in summer, and the fluff hides how thin it is. Long",
      "  coats mat over the days - brush them out, or they sell for less.",
      "- Clippers ($45, Care): click one of yours to shave its rear (nothing",
      "  sticks to it), again to shave it all over (cold, and the others",
      "  giggle). It grows back in three days.",
      "",
      "# Odd things they eat",
      "- Hot Peppers ($15): they look like a treat. Its mouth burns, it",
      "  cries and runs for water, and it won't eat from that bowl again.",
      "- A dim fluffy sometimes eats a block (or a pebble outside). Usually",
      "  a tummy ache; sometimes it gets stuck - no poopies, losing health",
      "  until the vet clears it ($70) or it passes in a day. Picking it up",
      "  mid-chew sets off a tantrum.",
    ],
  },
  {
    title: "Day, night & weather",
    lines: [
      "- A day is 20 minutes at normal speed. The clock by Chat Log shows",
      "  the day, time, season and weather.",
      "- Speed buttons (1x-8x) or F fast forward the whole game.",
      "- The moon button (\u263E, top right by Today): sleep until 7 AM. All",
      "  goes on while you sleep; the morning report says what happened.",
      "  It also skips ahead 1, 6 or 12 hours (anywhere, not just home).",
      "- Fluffies sleep mostly at night. Outside gets dark.",
      "- Seasons last 3 days (a year is 12): grass grows best in spring and",
      "  after rain, berries in autumn, almost nothing in winter.",
      "- Rain and snow upset fluffies outside; in the park they shelter",
      "  under trees. Thunder startles them. Snow makes them hungrier.",
      "- Every morning at 6:00 a report sums up the day before, and once a",
      "  week how the week went.",
      "",
      "# Cold and heating",
      "- Autumn nights and all of winter are cold outside; the house is",
      "  chilly in winter. The top bar says how cold it is where you are.",
      "- Cold fluffies (❄) get unhappy and hungry; freezing ones lose",
      "  health and can freeze to death - foals and the old first.",
      "- Huddling together, beds, scarves, wingjackets and park trees help.",
      "- A Heater (Fluff Mart, $400) keeps its room warm (outside: around",
      "  it). It runs only when it's cold, about $30 a day. Right-click it",
      "  to switch it off.",
    ],
  },
  {
    title: "Health & age",
    lines: [
      "The FluffVet Clinic is on Shopping Street. Click it: the vet makes",
      "house calls, so it all happens straight away.",
      "",
      "# The vet",
      "- Check-up $20: finds flu before it shows, and says how long an",
      "  old fluffy has left.",
      "- Treatment: cures flu, poison, toxoplasmosis and the runs, stops",
      "  bleeding and heals. Short of money? Click Treat again to pay",
      "  later (+25%).",
      "- Jabs: flu $40 (can't catch flu) and toxoplasmosis $60 (it can't",
      "  take hold). One button gives whichever it hasn't had.",
      "",
      "# Fluffy flu",
      "- Some wild fluffies and strays carry it. It's catching before it",
      "  shows, then they sneeze, feel miserable and lose health for about",
      "  a day. Foals and elderly fluffies can die of it.",
      "- It spreads to fluffies close by - but not through cage bars or",
      "  fences. Keep new arrivals in a cage or pen for a day or two.",
      "- Fluffies that get over it can't catch it again for a while.",
      "- Dead bodies left to rot spread it to fluffies nearby. Clever",
      "  herds carry their dead well away; dim ones leave them lying.",
      "  Clear them away in a trash bag.",
      "- Toxoplasmosis comes from eating poop off the floor and slowly",
      "  kills: keep floors clean, litter train, and jab them.",
      "",
      "# Scars",
      "- A bleeding wound from a fight, or from you, can leave a scar: a",
      "  torn ear, a bald patch, a kinked tail... (up to 5, for life).",
      "  The sorry stick only scars from a beating - 4 or more hits in one",
      "  go - not a whack now and then.",
      "- Each one takes 5% off the price (20% at most) and 3 points at",
      "  shows. Hover a scar in the magnifying glass to see how it happened.",
      "",
      "# Growing up and growing old",
      "- A season lasts 3 game days and a year 12, so each game day is",
      "  about a month of a fluffy's life. Fluffies live 6.5 to 8 years.",
      "- Foals grow up in about 2 months (2 game days); they walk at",
      "  about 3 weeks and mum nurses them until then.",
      "- From 4 years a fluffy is a senior: its mane and tail go grey.",
      "- From 6 years it's elderly: slower, worth half as much, and",
      "  elderly mares can't have foals any more. Elders calm their room.",
      "- Fluffies aren't built for running: after a few seconds of it they",
      "  run out of breath and can only walk until they've got it back.",
      "- From 6.5 years it can die peacefully of old age; none live past 8.",
    ],
  },
  {
    title: "Feelings, fears & wishes",
    lines: [
      "What goes on inside a fluffy: how it feels about you, what scares",
      "it, what it wants, and who it's becoming.",
      "",
      "# Giving up (\"wan die\")",
      "- A fluffy whose happiness hits zero gives up for good: it lies",
      "  down and stops eating. Today warns you when one is close.",
      "- A TPN drip (IV stand) keeps it alive; a bag lasts about a game",
      "  day. Drop spare bags on the stand, or right-click its AUTO tag to",
      "  buy new ones as they run out. Today warns before a drip runs dry.",
      "- Hunger and cages wear happiness down (not the Enclosure, $5000:",
      "  roomy enough to be happy in), but never below a fifth on",
      "  their own; it's the knocks on top (forced mating, hurting, losing",
      "  family) that tip a worn-down fluffy over.",
      "",
      "# Affection (the hearts)",
      "- Each fluffy you own has 0-5 hearts (magnifying glass, top right).",
      "- Up: brushing, filling its bowl, sketties, a present (hat, bow...),",
      "  a toy nearby, fixing a bleeding wound, the vet, giving it a name,",
      "  cuddles, praise. Only the first few of each a day count fully.",
      "- Down: hurting it or its family, a blindfold/gag/band, letting it",
      "  starve or freeze, hours shut in a cage. Ignored for 2 days, it",
      "  misses you and slowly cools off.",
      "- Loves you (4 hearts): comes to your hand, loves upsies and brushing,",
      "  forgives faster, shows and buyers like it. Under 1.5: it squirms.",
      "- Each loves one kind of care most (brushing, treats, play, praise,",
      "  presents or cuddles). Try them all to find out which.",
      "",
      "# Fears",
      "- Some fluffies are scared of thunder, the dark or the Fluff-Bot",
      "  (timid ones more often). See Fears in the magnifying glass.",
      "- A frightened fluffy trembles and cries, runs to its mum or a friend",
      "  or cowers. Pick it up or brush it to comfort it: that also makes the",
      "  fear smaller. Left to cry alone, the fear gets a bit worse.",
      "- Learnt fears: burnt with the hot iron (or seeing it), it fears the",
      "  iron in your hand and a hot heater. Seeing others culled in a cage",
      "  (or being inside), it dreads cages - even a plain one. Time in the",
      "  Enclosure slowly heals the fear of cages. Hurt during a bath, or",
      "  pulled out of the river, it fears baths and water: it panics at bath",
      "  time (a bath with no harm done eases it).",
      "- A big fright (thunder, the stick, a beating it saw, the mower close",
      "  up) can make it wet itself, or worse - timid ones most. Just mess:",
      "  it isn't a bad poopie.",
      "- Right-click a scared fluffy: Face its fear (gently, a little each",
      "  day) or Force it (harsh: a big step, but it may backfire and it",
      "  remembers you made it).",
      "- Night Light ($30, Fluff Mart): no fear of the dark in its room.",
      "- The Brave lesson shrinks every fear, the worst most. The table",
      "  lesson gets one over the operating table; Trust me, over fear of",
      "  you. Foals pick up mum's fears.",
      "- A Plushie ($25, Toys & Gadgets): one that sleeps or sits beside it",
      "  grows attached. With its plushie in the room it's frightened less",
      "  often and calms faster; take it away and it misses it. When its",
      "  owner dies, it goes to one of its foals.",
      "- Old fluffies steady the young: a frightened foal runs to one, and",
      "  a foal near an elder of its family slowly grows braver.",
      "",
      "# Taken away, and trauma",
      "- Carried away from its family, friends or herd, a fluffy misses",
      "  them, more as time goes on; bring it back and it's overjoyed.",
      "  Grown-ups get over it in time; young foals forget quickly.",
      "- Some things leave a scar on the mind for life (shown as Trauma):",
      "  being taken after you hurt it or its family, or killed its",
      "  family, or after its parents died. A foal torn from its mum",
      "  keeps a mild one.",
      "- Trauma means lower happiness, nightmares, and (if it blames you)",
      "  lasting fear of you - which also lowers its price.",
      "",
      "# Wishes",
      "- Now and then a fluffy wishes for one thing: a name, a trick, a",
      "  toy, a special friend, foals, the park, a hat, a warm bed...",
      "  (magnifying glass, Today, and ✦ on the Household screen).",
      "- Make it come true and it's overjoyed, then content for days.",
      "  Ignore it and it aches, then gives up. Take away what it wished",
      "  for and it remembers.",
      "- Right-click, Promise wish: it tries harder at tricks and lessons,",
      "  but breaking the promise costs a lot of trust.",
      "",
      "# Dreams, and who they become",
      "- Sleeping fluffies dream about their own lives: good dreams heal a",
      "  little, nightmares can wake them frightened - cuddle them.",
      "- What happens to them slowly changes who they are: comfort makes",
      "  them calmer, getting over a fear braver, being hurt more timid.",
      "- They call you by how you've treated them: Daddeh (or Mummah -",
      "  switch it on the Household screen), nice pewson, or munstah.",
    ],
  },
  {
    title: "Tricks, lessons & care",
    lines: [
      "Right-click one of your fluffies: tricks, lessons and care.",
      "",
      "# Jobs",
      "- Right-click a clever grown fluffy: Give it a job. A foal-sitter",
      "  comforts crying and frightened foals; a cleaner tidies small",
      "  messes. It learns by doing; a trained worker is worth more.",
      "",
      "# Tricks",
      "- Come, Sit, Lie down, Bow, Dance, Wave or Fetch. (Come: then click",
      "  where it should go. Fetch: needs a ball in the room; it brings it",
      "  back to you.)",
      "- If it gets it right, reward it straight away (Come and Fetch: when",
      "  it gets back to you): Good fluffy! (free) or a Treat ($2, teaches",
      "  more). No reward = it learns next to nothing.",
      "- 10 tries a day each. Fluffies that love you learn much faster;",
      "  playful ones and foals too, and clever ones (Smarts). Foals",
      "  watching pick a bit up.",
      "",
      "# The Auto-Trainer ($250, Toys & Gadgets)",
      "- Long-press or right-click it to pick the tricks and lessons to",
      "  work on, and praise or treats. It calls your fluffies in its room",
      "  over one at a time. A machine isn't you: they learn a bit slower",
      "  from it, and it earns you no love. It uses up their tries.",
      "- Known tricks (✓): +5% price each, +2 at every show, the Trick",
      "  Show, families like them, and some orders ask for them.",
      "",
      "# Kind or strict training (the switch above the tricks)",
      "- Strict: it tries even if scared. Punish a wrong try (Scold or",
      "  Smack). It takes about half as long again, costs trust and",
      "  happiness, and makes the room tense.",
      "- Tricks drilled with fear are done instantly and never refused,",
      "  but joylessly - show judges mark them down.",
      "",
      "# Lessons",
      "- Just the ones it needs: Colours (colour prejudice - a mare talked",
      "  out of it stops hurting her poopie foals), Alicorns (scared of",
      "  them), Litter, Be good (Smarties only), Brave (scared of things),",
      "  The table (scared of the operating table), Trust me (scared of",
      "  you - the one lesson a scared fluffy will still take), All babies",
      "  (a mare expecting or with foals: she'll never turn one away),",
      "  Play nice (a foal that bullies; needs a stuffy in the room).",
      "- 3 a day. Fluffies that love you listen far more often; foals too.",
      "- Be good is very hard: it rarely sinks in, a Smarty can dig its",
      "  hooves in, and it takes weeks. One that doesn't like you may never",
      "  change. Once reformed it's a normal fluffy (and learns tricks).",
      "- Fluff TV's Play Time channel also slowly teaches all colours are",
      "  friends to whoever watches.",
      "- Foals copy the grown-ups raising them, mum most: a prejudiced mum",
      "  raises prejudiced foals, a mum you've taught raises kind ones (and",
      "  one that accepts alicorns raises foals that do too). Teach mum first!",
      "",
      "# Care",
      "- Sit with: only when it's sad, grieving or frightened. It cheers",
      "  up, grieves less and trusts you more.",
      "- Praise: free affection, 3 a day. Party: only on real occasions",
      "  (a birthday, a welcome home, a new litter, a blue ribbon): paper",
      "  hats, bunting and confetti, and a memory everyone shares.",
      "- Scold: stops a fight, mischief or a mess at once, and teaches a",
      "  little (more to a clever one). It's a small thing - a little",
      "  trust - but scolding for nothing costs three times as much.",
      "- The spray bottle is a telling-off too, not harm - unless you",
      "  spray one more than 4 times in a day: then it's hurt, and it may",
      "  tell the others.",
      "- Scold just after it's done something worse and it learns: eating",
      "  another fluffy (less willing to again), a mum keeping milk from a",
      "  foal or hurting one (loves all her babies more), a grown fluffy",
      "  hurting a foal (calmer in time), a foal bullying (less prejudice).",
      "- Praise just after a good deed teaches too: a mum singing to her",
      "  foals, sharing her milk, taking in an orphan, feeding a foal she'd",
      "  have turned away; a foal standing up for one being picked on.",
      "- Time-out: a minute in a corner; it sulks and remembers.",
      "- Take a photo: it goes in the Memories book.",
    ],
  },
  {
    title: "Titles & breaking",
    lines: [
      "How you treat a fluffy over time can earn it a title.",
      "",
      "- Cherished: loved for 5 days running. Braver, calms its room,",
      "  worth more. Hurt out of the blue, it becomes Wary.",
      "- Survivor: came through harm and trusts you again. Startles easily",
      "  but is very loyal.",
      "- Broken: pushed past its breaking point. Numb, obeys anything, calls",
      "  you owna, dies sooner. Long patient care (Sit with, praise,",
      "  brushing, days without harm) heals it into a Survivor.",
      "- Rebel: a strong-willed one pushed too far. Won't obey, stirs the",
      "  others up, may run away. Win it round and it's a Guardian.",
      "- Guardian: stands up for others in fights. Spoiled: all treats, no",
      "  lessons - fussy and demanding until lessons fix it.",
      "- Each fluffy's breaking point is its own; strain fades with time.",
      "  The magnifying glass (Mind) shows which way it's heading.",
      "- Growing up with a Guardian makes foals braver; with a Broken",
      "  parent, more timid.",
      "",
      "# Rough tools",
      "- Shake a fluffy hard (wave it about while holding it): dizzy, and",
      "  it may wet itself or be sick.",
      "- Wall hook ($120, Hardware): set a fluffy down by it and it hangs",
      "  there, miserable and slowly hurt. Those who see learn to fear the",
      "  hook. Pick it up to take it down.",
      "- Hook pole ($60): drags a fluffy over, or a hidden foal out of its",
      "  hiding place. It hurts.",
      "- Hot plate ($80): right-click to switch on. Set down on it (or held",
      "  against it) a fluffy is burnt: a scar, a fear of fire, sore and",
      "  slow for a day and a half. The vet can dress it.",
      "- Defibrillator ($1200, Pharmacy): a grown fluffy that's just died",
      "  (within a few seconds) may come back. It never forgets.",
      "- Lethal ($150, a syringe drug): a full dose and it falls asleep and",
      "  dies quietly a little later.",
    ],
  },
  {
    title: "How a room feels",
    lines: [
      "Each room gets a feel from what happens in it over a few days.",
      "",
      "- Shown next to the room's name: Warm, Calm, Uneasy, Tense,",
      "  Fearful or Grieving, with an arrow. Hover it to see why.",
      "- Warm: brushing, play, treats, praise, lessons, parties.",
      "- Tense: fights, crowding, scolding, strict training.",
      "- Fearful: hurting fluffies, frights. Grieving: a death, family gone.",
      "- It nudges happiness, how well they learn, and how much they play.",
      "- You can see it: the room takes on a faint colour (golden when",
      "  Warm, reddish when Tense, dark at the edges when Fearful, washed",
      "  out when Grieving). In a tense or fearful room fluffies huddle",
      "  close to a friend or their mum.",
      "- At the door: loving ones run to you in a warm room; scared ones",
      "  scatter. Fluffies that fear you flinch when your hand comes near.",
      "- Ears tell you too: a sad, grieving, scared or Broken fluffy's",
      "  ears hang back.",
      "",
      "# Crowding",
      "- A room has space for about 20 fluffies, the backyard 30 (a foal",
      "  takes half a place). Over that, everyone there gets unhappier and",
      "  grumpy ones start shoving. The room name at the top turns red.",
      "",
      "# Gossip and sleeping piles",
      "- Fluffies tell each other about you. One that saw you hurt someone",
      "  makes its friends wary; one that loves you settles newcomers in.",
      "- Friends asleep near each other shuffle up into a heap (a foal",
      "  tucks in by mum), and waking beside a friend makes them happier.",
      "- They only know the fluffies they've met: in the same room as them.",
      "  A stallion doesn't miss a foal he's never seen; the house doesn't",
      "  know the strays in the backyard.",
      "",
      "# Blankies, lights and stories",
      "- A Blankie ($15, Home & Housing): leave it by a mum while she rests and",
      "  it smells of her. Her foal, kept apart from her, settles by it. If",
      "  it gets soiled and you take it away in front of the foal, that's",
      "  \"bad poopies\" - it's ashamed and a little more timid.",
      "- The 💡 chip (top bar) leaves a room's lights on all night: easier",
      "  to watch, but they rest half as well. Two nights running and they",
      "  lose track of the days.",
      "- A mum who lost her foals: right-click her, \"Tell her: at da vet\".",
      "  She cheers up and waits - for two days. Then she works it out,",
      "  and trusts you less.",
      "- Fluffies who see room-mates taken away (or culled) tell stories",
      "  of \"da towew\": frightened, better behaved, bad dreams. It fades.",
      "- A gentle fluffy picked on again and again bottles it up - then on",
      "  the fifth time it snaps and hurts the bully badly. The others are",
      "  wary of it after.",
      "- A room crowded for a whole day breaks down (\"breaking down\" by",
      "  its name): mums stop nursing, grown-ups go listless (fluffies in",
      "  cages are spared). Thin it out and it settles again.",
    ],
  },
  {
    title: "Stories, names & memories",
    lines: [
      "Every fluffy's life is written down as it happens.",
      "",
      "# The Story tab (magnifying glass)",
      "- Its life in chapters: before you, as a foal, young, grown, old.",
      "- Turning points pop up as a message: first steps, walking up to",
      "  you, first words, a name, a first trick, a new title.",
      "- Big moments you share, notes from new owners, photos.",
      "",
      "# The Mood tab (magnifying glass)",
      "- Its mood as a bar, with the \"wan die\" zone in red and a",
      "  marker for where it settles if nothing else happens.",
      "- Lasting: what moves where it settles - a wish come true, the feel",
      "  of the room, being afraid of you.",
      "- Lately: what's raised or lowered it in the last few hours",
      "  (hungry, played, scolded, a friend died...), biggest first.",
      "",
      "# Names",
      '- Fluffies are just "Fluffy" until a person names them. Runaways,',
      "  abandoned and lost pets, and breeders' stock come with a name.",
      "- When a fluffy becomes yours (born, bought or brought home) a",
      "  pop-up offers to name it; a litter gets one pop-up for all foals.",
      '  Leave a box empty to keep it "Fluffy"; rename any fluffy later',
      "  with the magnifying glass.",
      '- \u{1F3F7} gives a stock tag instead ("Stallion-01", "Milkbag-02",',
      '  "Colt-03"...; "Tag all" for a litter): no affection in a tag.',
      "- The magnifying glass shows its stage (Chirpy, Talkie, Walkie,",
      "  Adult) and colour tier (1 prized ... 4 poopie).",
      '- Unnamed fluffies are described by their looks: "Fluffy (pink',
      '  unicorn mare)". They call each other by name, or a nickname like',
      '  "wingy-fwen".',
      "",
      "# The Memories book (Household, Memories book)",
      "- Moments: storms, births, deaths, fights, show wins and parties that",
      "  several fluffies went through together. Rename them if you like.",
      "- Lives: when one of yours dies, its story closes with an epilogue.",
      "  Click Read to go through it again.",
      "- Photos: right-click a fluffy, Take a photo. Click a caption to",
      "  change it.",
      "- A year on, a sad memory makes its room grieve again; a happy one",
      "  cheers everyone who was there.",
      "",
      "# The memorial tree ($200, Home & Housing)",
      "- Its plaque remembers every fluffy of yours that dies (right-click",
      "  or long-press the tree to read it). Stillborn foals aren't on it.",
      "  Tap a name to read that fluffy's life story.",
      "- Those close to one who died mourn it for a couple of days. With a",
      "  memorial tree in their room they go and sit by it now and then",
      "  (or carry them there): it comforts them and eases the grief.",
    ],
  },
  {
    title: "Breeding & foals",
    lines: [
      "How you look after a pregnant mare decides how her litter turns out.",
      "",
      "# Pregnancy",
      "- Pregnancy takes about 2 weeks (half a game day). After a litter a",
      "  mare rests for about 5 weeks (just over a game day) before she",
      "  can get pregnant again.",
      "- Care: fed, happy, healthy, rested and not scared of you. The",
      "  magnifying glass shows it (Great / Good / Fair / Poor) and when",
      "  she's due.",
      "- Poor care: she loses foals before birth, more are stillborn, and",
      "  the foals are born weak. Great care: strong foals that grow faster.",
      "- Litter size runs in families: mares and stallions from big",
      "  litters have big litters (up to 10). Seniors have fewer.",
      "- Big litters are hard to carry: with more than 4 foals, each",
      "  extra one makes a miscarriage likelier (about a third at 10).",
      "  Good care helps a little; the vet warns you.",
      "- Hereditary defects run hidden in families: a foal of two carriers",
      "  may be a \"dummy foal\" (grunts, can't nurse, simple) or have shaky",
      "  legs (falls over, misses the litterbox). The vet's breeding advice",
      "  has a DNA test ($40): it shows carriers, and the advice then warns",
      "  of the odds for a pair.",
      "- A mum who's seen a cull or a sale may hide a deformed, runt or",
      "  poopie foal under a bed, in a box or the litterbox. You'll find it",
      "  if you move what it's under - or a snitch tells you.",
      "- Every birth costs her health, more with a big litter. A check-up",
      "  at the vet scans her: how many, and whether it's risky. Book a",
      "  midwife ($60) for a safe birth.",
      "- Foals grow faster when they're well fed. Hungry ones slow down.",
      "- Walking foals still drink from a feeder or a mare until about half",
      "  grown, when there's nothing in a bowl for them.",
      "- A mare held on a rack or table gives birth where she is (her IV",
      "  drips stay in); otherwise she goes to her bed if it's close.",
      "- Near her time, and for a few hours after the birth, a mare hardly",
      "  moves: she lies down and rests, and only gets up to eat, use the",
      "  litterbox or go to her bed.",
      "",
      "# Born early",
      "- Mating a pregnant mare, or a hard landing when she's thrown,",
      "  brings labour on early. How far along she is decides it:",
      "  under 40% the foals are all stillborn, and tiny; 40-65% very",
      "  premature - most die, survivors are very small and weak; 65-90%",
      "  premature - most live, small and a little weak; after that, normal.",
      "- Early foals catch up in size as they grow. A midwife gives each",
      "  one a better chance.",
      "- Very premature and premature foals are frail for most of their",
      "  time on milk: cold or hungry, they weaken and can die. Keep them",
      "  warm and fed - or put them in an incubator.",
      "- Mum comes to the incubator's glass now and then (or carry her",
      "  there). Left too long without a visit, she may not know her foal",
      "  when it comes out, and won't nurse it.",
      "- Born very early, it catches the flu more easily all its life.",
      "",
      "# Family and breeding",
      "- Fluffies won't breed with close family (parents, foals, brothers",
      "  and sisters, half-siblings, grandparents, aunts and uncles) or pair",
      "  up with them - unless you make them, or something's wrong with the",
      "  one doing it: a Smarty, a Broken fluffy, a killer, one with",
      "  toxoplasmosis, or one on an aphrodisiac. Cousins still can.",
      "- Inbreeding: foals of close kin (cousins or closer) may be born",
      "  deformed - simple-minded, a crooked leg, wing or horn, sickly",
      "  (catches things easily) or odd (says and does strange things).",
      "  Brother and sister: about half their foals. A foal with a bad",
      "  pair of genes that would be stillborn often pulls through when",
      "  its parents are kin - alive, but always deformed. Each deformity",
      "  takes 15% off the price.",
      "- Sensitive babies run in families: a sensitive mum or dad makes",
      "  sensitive foals far more likely. A sensitive fluffy can only be",
      "  bred in a breeding cage, and it wears it out: each litter its",
      "  health can only get back to less (\"Worn out\"), healing a little",
      "  each day. Too worn and it can't be bred.",
      "- The Gene Lab's Planner: pick what you want (type, coat, mane,",
      "  pattern, fancy mane) and it lists which of yours already look",
      "  like that, and your best pairs for it, with the chance per foal.",
      "- Related parents have more foals that don't survive. The vet's",
      "  Breeding advice (bottom of the vet screen): pick a fluffy to see",
      "  how related it is to each of yours, how many foals would be born",
      "  alive, and its best matches (\u2605). The family tree shows how",
      "  related each card is to the one in the middle.",
      "- Newborns ride on mum's back until they can crawl (about a week",
      "  and a half); she goes back for one left behind.",
      "- Orphans: a mare who's lost a foal of her own (her milk comes",
      "  back), or a gentle one nursing her own, may take in an orphan",
      "  nearby - wild mares wild orphans, your mares your orphans. It's",
      "  hers from then on, and they stay close for life: sell or give",
      "  away one and the other grieves. Her foals take to it, and the",
      "  family tree shows its foster mum with a dotted line.",
      "- Only the worst mums (nasty-tempered, and colour-snobby or",
      "  unstable) pick a \"bestest babbeh\" - the foal most like her or her",
      "  special friend. It gets the last of the milk, and its brothers and",
      "  sisters resent it, even grown up. A good mum loves them all the",
      "  same; an ordinary one feeds a poopie-coated foal last when the",
      "  milk runs low.",
      "- When two of yours want to be special friends in the room you're",
      "  in, you're asked: let them, or keep them apart (they won't ask",
      "  again for a few days). Elsewhere they decide for themselves.",
      "- Special friends stand by each other: one that sees its partner",
      "  hurt cries out (a brave one fights back), and it's upset to see",
      "  its partner bred by someone else.",
      "",
      "# Mothers and foals",
      "- The mummah song: mums sing to their foals at bedtime and when",
      "  they're scared. It ends a fright, makes them sleepy, and that night",
      "  thunder and the dark often don't scare them. Foals learn it after",
      "  hearing it 3 times; a mare who never learned it can't sing it.",
      "- Runts: some foals are born small and weak (more in big litters,",
      "  between kin, after a hard pregnancy). They grow slower and sell",
      "  for less.",
      "- A mum may sniff a runt, a deformed or a sick foal and turn it away",
      "  (\"nu smeww pwetty\"): no milk from her. A foster mum, a feeder",
      "  or the Feed-Bot has to feed it. The All babies lesson stops it.",
      "- Last chance: right-click a mare with foals. If she keeps the milk",
      "  from a foal, hurts one or turns one away, each time costs her:",
      "  time away from her foals, then her bestest, then all of them (to",
      "  a foster mum with milk). Good behaviour wins strikes back.",
      "- Foals kept in another area from mum forget her (hours for a",
      "  chirpy, longer when older): no milk from her, no running to her.",
      "  Time near her again and it may know her again.",
      "- Curious foals crawl off on their own - even to the water's edge.",
      "  Mum notices, calls and goes to fetch them.",
      "- Young foals and simple-minded grown fluffies don't understand",
      "  death at first: they think a body is asleep, try to nurse from a",
      "  dead mum or wake a dead friend, and only grieve once they",
      "  understand (or it starts to smell). Clever ones know at once,",
      "  even as foals.",
      "- A mare has two teats: only two foals drink at once; the rest",
      "  wait their turn.",
      "- Foals may pick on an alicorn or poopie-coated foal (\"munstah!\")",
      "  and shove it off the milk: it grows timid, the ringleader a bully.",
      "  Teach a bully Play nice (a lesson; needs a stuffy in the room):",
      "  it takes it out on the stuffy instead and makes up with it.",
      "  Once taught, it goes to a stuffy instead of a foal by itself.",
      "- No prejudice, no bullying: Colours and Alicorns cure the cause",
      "  (and the snubbing), Play nice only the shoving.",
      "- A foal that grows up a bully keeps at it, picking on alicorns and",
      "  poopie coats of any age, until it's taught Play nice. Foals raised",
      "  by a bully pick up the habit. Fully taught, it grows up calmer,",
      "  stands up for others, and its own foals don't learn to bully.",
      "",
      "# Discipline",
      "- Right-click a grown fluffy: No mating. Most of the time it holds",
      "  off. If it mates anyway, Discipline: a scolding, then a time-out,",
      "  then the stick, and last of all spaying or neutering.",
      "",
      "# Coat colours",
      "- Brown coats (and rust, tan, dark olive) are poopie: a colour-proud",
      "  mum rejects a poopie foal - no milkies, and she'll hurt it (Today",
      "  warns you: keep them apart). The Colours lesson cures her.",
      "- Other colours are fine, but drab or faded ones (grey, black,",
      "  pastels, muddy colours) get snubbed more than bright ones, and",
      "  bright coats sell for the most.",
      "",
      "# Fancy manes",
      "- A few fluffies have a streaked or tipped mane (and tail) in a",
      "  second colour, or very rarely a rainbow one. Worth more, and",
      "  judges and collectors love them.",
      "- They run in families like spots: two parents with one always",
      "  pass it on. The Gene Lab shows the odds; Prism Stables (stock",
      "  market, from Trusted breeder) breeds them.",
      "",
      "# Family lines",
      "- A line is everyone descended from the same first mother. With 3",
      "  or more of them with you, it earns a name: famously gentle,",
      "  clever, brave, known for its tempers... (magnifying glass, Line).",
      "- Traditions: if a mare and her mother both know a trick, her foals",
      "  learn it from her while they're little.",
      "- Echoes: a foal that grows the same fear as its grandmother gets",
      "  a line in its story.",
    ],
  },
  {
    title: "Smarties & alicorns",
    lines: [
      "# Smarts",
      "- Smarts, 0-100, in the magnifying glass. On average earthies 50,",
      "  pegasi 35, unicorns 60, alicorns 90 - and each fluffy up to 25",
      "  either side: wits run in families (Clever / Dim). Clever ones",
      "  learn tricks, lessons and the litterbox faster.",
      "",
      "# Smarties",
      "- Smarties are a bit cleverer than the rest of their breed (+8, a",
      "  good one +15): a pegasus smarty is still no genius.",
      "- Most are bad smarties. A good smarty (rarer; more often among",
      "  clever breeds) is cleverer still and kind: it acts like any good",
      "  fluffy and makes a careful leader - its herd is calmer and happier.",
      "- Bad smarties are bullies: now and then they shove someone out of",
      "  the way, but they leave their own herd, family and friends be -",
      "  unless they have a poopie coat: that they never tolerate.",
      "- A bad smarty leading a herd leads it to ruin: bossy and harsh, its",
      "  herd grows unhappy, falls out, and breaks apart.",
      "- When things go wrong a bad smarty saves itself: it runs from a",
      "  fox and may desert its herd then - or when the herd is losing a",
      "  war, starving or sick. The herd picks a new leader and won't",
      "  forget it.",
      "- Hit one, or leave one miserable, and it picks real fights.",
      "- A starving fluffy may eat another - a body first, the weakest",
      "  living one if it's desperate - but only one with it in it (a nasty",
      "  temper, a bad smarty, a broken one). A good fluffy never would.",
      "- Eating fluffy - the machine's meatballs, or a body - often enough",
      "  can bring the wobbles: hidden for days, then slow and stumbling,",
      "  then death. Nothing cures it, and the inspector notices.",
      "- Make a grown fluffy a snitch (right-click): every hour it tells",
      "  you, for a treat, what goes on in its room - a hidden foal, a mum",
      "  keeping milk back, a bully. The others don't like a tattletale.",
      "- They chase mares for enfies every few hours, and only go after",
      "  a pregnant one when there's no other mare around.",
      "- The Be good lesson can reform one, slowly (Tricks, lessons & care).",
      "",
      "# Alicorns",
      "- With alicorn intolerance on, most fluffies are scared of alicorns.",
      "  Getting one to accept them is rare and takes a long time:",
      "- Only time spent near an alicorn that doesn't hurt anyone helps:",
      "  weeks of game time, and they forget if you keep them apart.",
      "- A little faster for foals, brave fluffies, a mum with her own",
      "  alicorn foal, friends who already accept them, or a caged alicorn.",
      "- A fluffy that really trusts you can be held near the alicorn to",
      "  introduce them. It takes a long time.",
      "- Smarties almost never come round. An alicorn attack sets them",
      "  right back.",
      "- A mum who does accept her alicorn foal takes it back.",
      '- The magnifying glass shows it: "Alicorns: Getting used to them (40%)".',
      "- Foals, and hurt or frightened fluffies, run from one. Most grown",
      "  ones just steer clear of it. A fierce one (brave, bad-tempered,",
      "  or a Smarty) goes for one that's weak - a foal, hurt or lame - a",
      "  few blows, then it leaves it be for a while.",
      "- A few fluffies (about 1 in 12) simply don't care about alicorns.",
      "- Most don't grieve a dead alicorn foal.",
    ],
  },
  {
    title: "Selling & reputation",
    lines: [
      "How you treat a fluffy changes what it's worth, and who buys it.",
      "",
      "# Temperament and price",
      "- Happiness, trust in you, and not being afraid of you all count;",
      "  lasting trauma counts against it.",
      "- Temperaments: Delightful pet, Good-natured, Ordinary, Nervous,",
      "  Damaged. Prices range from about 0.4x to 1.3x.",
      '- The magnifying glass shows it: "Sells for $240 (Good-natured +12%)".',
      "- Litter training adds up to +50%; tricks, ribbons and a title add",
      "  more. Scars, poor health and missing parts take it off.",
      "",
      "# Buyers at the door",
      "- A family wants a friendly one, a kid a foal, a farmer a grown",
      "  earthy, a collector rare colours and types, a show breeder a prize",
      "  winner. They ask about the one they like best (sell cage first).",
      "- Poor health, missing parts or flu showing lower the offer.",
      "- Ask more (20% more): they may agree, name a final price, or walk",
      "  off. Slow market days bring half as many buyers; busy days more.",
      "- Also: a care home (a calm grown-up), a worried parent (a gentle",
      "  one - never a biter), a research lab (only for sensitive babies,",
      "  defects and deformities; families hear of it), and an influencer",
      "  who pays well for a cute foal - and dumps it in the park a week",
      "  later under a new name.",
      "",
      "# Your two names",
      "- New owners write a day or so after a sale: praise for a clever,",
      "  loving fluffy, complaints if it bites, hides or cries all night.",
      "  Good notes bring more families, and they pay a bit more.",
      "- The shady dealer turns up now and then and pays well for Broken,",
      "  drilled or stick-conditioned fluffies - and little for happy ones.",
      "  Selling to him grows your dark name, and families hear of it.",
      "- Sell the lot: right-click one in a sell cage to sell the whole",
      "  cage to the pet-shop van at about half price, once a day.",
      "- Both names are shown at the top of the Household screen.",
    ],
  },
  {
    title: "Orders, stock & shows",
    lines: [
      "Three tabs on the Bounty Board (Shopping Street) and FluffList (the",
      "Computer): customer orders, breeding stock, and shows. FluffList",
      "also has a Food tab: order food for delivery.",
      "",
      "# Orders and customers",
      "- Take up to 3 at a time. Some ask for tricks, or for one \"raised",
      "  gently (no lasting trauma)\"; customers tip for a delightful fluffy.",
      "- Commissions (gold cards): the customer wants one BRED by you,",
      "  with a few days to deliver. They pay about 2.5x a normal order,",
      "  with a deposit when you accept. A new one every day; alicorn",
      "  commissions from day 4. Plan a pairing in the Gene Lab.",
      "- FluffList has its own exclusive commission too (purple): harder,",
      "  about 3.5x a normal order, a day longer. Give up or run out of",
      "  time and the deposit goes back, and your reputation takes a",
      "  bigger hit.",
      "- Customers remember you. Fill their orders (better still with a",
      "  friendly fluffy they adore) and they come back as Returning,",
      "  Regular and Loyal customers, paying up to 25% more with more",
      "  time. Let them down twice and they stop ordering for a few days.",
      "- Some write later about how their fluffy is doing - with a tip",
      "  if they love it, a complaint if it's frightened of everything.",
      "- Each customer has a favourite type they often ask for.",
      "",
      "# Breeding stock",
      "- Other breeders sell pedigree fluffies. New stock every morning.",
      "  Each breeder has a line: spots, stripes, white coats, wings,",
      "  horns, pastel colours or cheap hardy earthies.",
      "- The card shows the fluffy, its mum and dad, and its grandparents.",
      "  A spotted grandma or pegasus dad means it may carry those genes",
      "  hidden. After buying, the family tree and Gene Lab show them.",
      "- Better reputation, better stock: unicorns and pegasi from Known",
      "  breeder, more choice and the odd alicorn from Renowned breeder.",
      "- Stock costs about twice what a buyer would pay for it: you buy to",
      "  breed, not to sell on.",
      "",
      "# Fluffy shows",
      "- Every 3 days at 2 PM, in the Show Hall on Shopping Street.",
      "- Each show has a theme: Best Coat, Spots & Stripes, Best Unicorn,",
      "  Best Pegasus, Friendliest, Best Foal, Golden Oldies, Best Behaved,",
      "  Trick Show. From Trusted breeder, sometimes a Supreme Championship.",
      "- The tab lists the fluffies that can enter, with the judges' score.",
      "  Coat colours count most, then temperament (happy, trusting, calm).",
      "  Missing parts, scars, flu or poor health cost points.",
      "- Enter one fluffy for a small fee (withdraw for a refund before",
      "  the show). The other breeders get better as your reputation grows.",
      "- Brush your entry within a day of the show: +5 with the judges.",
      "- You watch it in the ring: the parade, the scores, the podium.",
      "- 1st, 2nd and 3rd win money, reputation and a ribbon. Ribbons raise",
      "  a fluffy's price, and 3 wins make it a Champion.",
    ],
  },
  {
    title: "The shelter",
    lines: [
      "Right of the alley, through the shelter door.",
      "",
      "- The desk boards your own fluffies ($30 a day each, with the",
      "  bills). Boarders get lonely, and can die of old age while you're",
      "  away. You can also give one of yours up there instead of selling it.",
      "- Or set a fluffy down on the after-hours drop box outside: a stray",
      "  goes straight in; one of yours, you're asked first.",
      "- The kennels hold strays and fluffies nobody wanted. All you can",
      "  read is the plaque, and the staff are kind about the truth:",
      "  \"Spirited!\" can mean grumpy. Mostly drab or poopie coats and",
      "  poor manners, but now and then a gem.",
      "- Each has a time's-up day. On its last day it's half price.",
      "  There are 16 kennels.",
      "- The playpen in front of the desk: a few of the shelter's cutest",
      "  foals, put out to tempt you. Tap one to adopt it. Ones that grow",
      "  up find homes with other people, and new ones come out.",
      "- Some are broken fluffies rescued from dealers. Heal one (from",
      "  Broken to a Survivor or Cherished) and families hear of it.",
      "",
      "# Abandoned fluffies",
      "- Some pets are dumped by their owners: half-grown, grown up or",
      "  old. They have a name, and they miss their old owner, so they're",
      "  sadder (and sell for less) until they get over it - faster once",
      "  they're yours and trust you.",
    ],
  },
  {
    title: "Fluffy Park",
    lines: [
      "The park is to the right of the Shelter Alley. It's bigger than the",
      "screen: drag the grass, scroll, or use WASD / arrow keys to look",
      "around. Click the map in the corner to jump.",
      "",
      "- Wild fluffies live there in herds, eat the grass in the meadows and",
      "  berries from the bushes, and breed on their own. Wild mares have",
      "  fewer foals when food is short (winter, or a crowded park).",
      "- To take one home, just carry it out through the exit arrow.",
      "- Wild fluffies are wary of people: fresh from the park they're",
      "  Nervous and sell for less. With good care they settle in (the",
      '  magnifying glass shows "Settling in").',
      "",
      "# Herds and territory",
      "- Fluffies that like each other form herds with a leader (press H to",
      "  see herd markers).",
      "- In the park, herds claim meadows. Their colour rings the meadow on",
      "  the park and the map.",
      "- They chase strangers off their land, and a bigger herd can take a",
      "  meadow from a smaller one. Herds over 12 split in two.",
      "- Rival herds keep apart: no hugs, friendships or sleeping together.",
      "  Not under your roof: your fluffies can make friends whatever herd",
      "  they came from. Forget herd (right-click it, long-press on a phone,",
      "  or Actions in the magnifying glass) has it leave",
      "  its old herd (it keeps its friends); it joins a herd here once it",
      "  has made friends.",
      "- Herds need food, so winter (when little grows) brings more fights.",
      "- Feuds: a herd driven off its meadow, or whose members are hurt",
      "  or killed by another herd, holds it against them (magnifying",
      "  glass, Feud). Bad enough, and the two go to war: their grown",
      "  members charge each other and fight for a while. Wars feed the",
      "  feud, so they come back. Feuds fade over days.",
      "- Herd jobs (magnifying glass, Herd job; the map): toughies (brave,",
      "  grumpy, mostly earthies) guard, chase off anyone who hurts the",
      "  herd's foals, and do the fighting in wars. Nummy finders bring food",
      "  to nursing mums and the sick. A bad smarty's toughies keep the",
      "  others in line with a shove; a good smarty's herd is fed first.",
      "",
      "# Trade and tools",
      "- A reptile shop buyer sometimes calls for runts, poor colours and",
      "  old ones: he pays a little by weight, and families hear of it.",
      "- Fake alicorn (right-click an earthy, pegasus or unicorn): a glued",
      "  horn and wings. It sells like an alicorn until a buyer, the vet or",
      "  the inspector notices (refund, a bad name, a fine). Baths undo it.",
      "- Mystery carrier (Computer, Food tab, $120): any type, colour or",
      "  age - sometimes rare, sometimes a dud.",
      "- The pause menu has a birth buzzer and Newborns to incubator. Milk",
      "  her (right-click a nursing mare): a bottle sold to the mill.",
      "- Stay little (right-click a foal): a day's formula and it doesn't",
      "  grow (half as well near other grown-ups). Worth more; stop and it",
      "  grows up confused and timid.",
      "- Surgery can pull teeth (kibble hurts) or cut out the tongue (it",
      "  only cries). The Auto-amputator (Surgery & Restraint) takes every",
      "  limb at once.",
      "- Swing a fluffy round in circles: dizzy, sick, and it remembers.",
      "- Rat poison poured into a bowl of food mixes in unnoticed. Those who",
      "  see someone sick from it won't eat from that bowl.",
      "- Talk (right-click): tell it what it did wrong (a better lesson",
      "  than scolding, just after), call it a bad fluffy, or cruel words.",
      "",
      "# Summer, microfluffs and sensitive babies",
      "- Summer afternoons are hot outside (the house gets stuffy). Hot",
      "  fluffies wilt and get thirsty; too hot and they get heatstroke and",
      "  can die - foals and the old first. Shade under park trees, a water",
      "  bowl, the sprinkler, a fan or staying indoors help. At night they",
      "  greet the moon: the \"nu-hawt-baww\".",
      "- Fluffies call summer the \"hawt-times\" and winter the",
      "  \"cowd-times\" - once they've lived through some of it (or are a",
      "  year old, or clever). The first time, they don't know what's",
      "  happening to the bwight-baww.",
      "- Microfluffs: a tiny, fragile breed - a grown one is no bigger than",
      "  an ordinary newborn, and its own foals are far smaller. Falls and",
      "  blows hurt them badly; they eat little and fit several to a cage.",
      "  Rare in the park, loved by collectors. They can only breed with",
      "  other micros, and their foals are always micro.",
      "- A sensitive baby looks normal at first: its head swells around",
      "  first words, its neck and belly later. The vet can tell early.",
      "- Surgery shows the fluffy's face up close and what it says.",
      "",
      "# Raids, lures and the machine",
      "- Leave food, a stuffy, a bed or toys in the garden, the alley or",
      "  the backyard and more strays come. Sketties draw greedy ones, a",
      "  stuffy or toys draw foals, good kibble a tame lost pet with nice",
      "  colours. In the backyard they come in through the gate.",
      "- Lures in the backyard also draw raids: a wild herd (often with a",
      "  bad smarty) comes in, eats everything and tries to claim the yard.",
      "  Your grown fluffies there fight back, toughies first. Chase them",
      "  off with the red button at the top of the backyard. The best",
      "  fence keeps raids out.",
      "- The Foal-4-Sketties machine (Hardware) keeps wild herds small: a",
      "  hungry herd nearby trades it a foal for sketties and meatballs, and",
      "  the foal doesn't come out. Stock it by long-press or right-click.",
      "  A good smarty never trades. Herds that see it work fear it, and",
      "  some realise what the sketties are made of.",
      "- Places you're not in keep going, but strays come and go there. A",
      "  stocked machine draws hungry families to it, and they wait by it.",
      "",
      "- Strays outside move on when they're hungry, crowded or bullied:",
      "  between the garden, the river, the alley, the road and Shelter",
      "  Alley, or on into the park. Never into your house or the shops.",
      "",
      "# Night in the park",
      '- Most nights something happens to a herd ("Last night in the park"',
      "  in the morning report).",
      "- Bad: a fox goes for the weakest, usually a foal (brave fluffies",
      "  and the leader stand up to it; click it to chase it off); a tummy",
      "  bug, a stampede that tramples the meadow, a fight in the herd.",
      "- Good: a bumper crop, newcomers joining, a snuggly night. Rarely a",
      "  lost pet wanders in: good genes and not afraid of people.",
      "",
      "# Outings",
      "- Right-click one of yours at home: Park outing takes everyone in",
      "  that room who can walk to the park with you. They play (happier,",
      "  less bored), meet the wild ones and stay near you. Home time (the",
      "  banner at the top), or leaving the park, walks them all home.",
      "- Herds that have heard you're kind come over to say hello; herds",
      "  that have heard you hurt fluffies keep away from you and yours.",
      "",
      "# Runaways",
      "- A Rebel, or a fluffy that fears you and has lost its trust in",
      "  you (or is miserable), may make for the front door one day (it's",
      "  on Today). Fear of you takes a few days to fade. Pick it up or",
      "  comfort it and it stays; otherwise it's off to the park. In the park,",
      "  right-click one of yours to Let it go.",
      "- Either way it tells the wild ones about you. Herds that hear",
      "  you're kind warm to you; herds that hear you hurt fluffies don't.",
      "  The magnifying glass shows what a herd has heard.",
      "- Spot an old fluffy of yours in the park and it runs to you or",
      "  bolts. Right-click it to bring it home, if it still trusts you.",
      "  On an outing, old friends and family who meet again are overjoyed.",
      "- A herd led by a Rebel that ran away from you (or one of your old",
      "  fluffies, when they've heard bad things about you) may raid the",
      "  backyard at night: they eat the food and start fights until",
      "  morning, and a miserable fluffy of yours may leave with them. Go",
      "  out there and they scatter. A sound fence keeps most raids out.",
      "- The basic backyard fence breaks every few days; the better one",
      "  about every two weeks.",
      "",
      "# Dogs, the street sweep and glue traps",
      "- Now and then in the day a stray dog runs through the alley or the",
      "  park. Everyone scatters; a mum grabs one foal (her bestest, if she",
      "  has one) and leaves the rest. It bites the weakest it can catch -",
      "  a small foal doesn't survive. Click it to chase it off.",
      "- Once a week the city's street cleaners come through the alley at",
      "  dawn and take every stray and body there. You're warned the day",
      "  before; yours are left alone.",
      "- Glue traps (Fluff Mart, Hardware, $15) catch whatever walks onto",
      "  them - strays, raiders, your own. Pick a stuck one up and it tears",
      "  free (it hurts); right-click the trap for cooking oil ($3).",
      "",
      "# The wild",
      "- Foals born wild get a little smaller and rougher each generation,",
      "  and sell for less. A former pet has a collar mark.",
      "- In winter, strays sleeping out alone can freeze to the ground:",
      "  pick it up to tear it free (it hurts), or warm it. Herds build",
      "  dens to sleep in.",
      "- Wild fluffies cover their dead with leaves.",
      "- A bad smarty may call your fluffies over the backyard fence. The",
      "  unhappy ones that don't trust you go. A strong fence stops it.",
      "- A big herd settled in the alley keeps the neighbours up: they",
      "  complain, and your name with families slips if it goes on. Pest",
      "  control ($100) clears the alley; a Bin fence ($150, Hardware)",
      "  keeps strays from settling there at all.",
    ],
  },
  {
    title: "Money trouble",
    lines: [
      "Every morning you pay the bills. They're on the day report, and in",
      "Accounts (click your money, top left, or press K). What you can't pay",
      "is owed, and comes out of the next mornings' money first.",
      "",
      "# The bills",
      "- Rent: $20, plus 12% of an average day's net takings last week",
      "  (sales, orders, prizes and items sold, less fluffies you bought).",
      "  The landlord reviews it once a week: it can double after a good",
      "  week, and comes down more slowly after a bad one.",
      "- Rooms: $15 for the first extra room, $10 more for each after that.",
      "  Fluffies: $5 each (foals half).",
      "- Heating: in autumn and winter, for each room your fluffies are in,",
      "  plus what the heaters used. None while the power's cut off.",
      "",
      "# The vet plan and loans",
      "- The FluffVet plan (at the vet, or in Accounts): a daily premium",
      "  for all your fluffies; from the next day check-ups are free and",
      "  treatment and midwives cost a quarter.",
      "- The landlord lends up to 3 times last week's takings (at least",
      "  $500). You pay back 20% more over 10 mornings, with the bills;",
      "  pay it off early any time. One loan at a time.",
      "",
      "# Falling behind",
      "- Day 1 in debt: a final notice. Day 3: the power's cut off and the",
      "  heaters stop. Day 5: the bailiffs take your most valuable grown",
      "  fluffy. Pay it off and everything goes back to normal. With no",
      "  grown fluffies left to take, the landlord writes the debt off.",
      "- Can't afford the vet? Click Treat again to pay later (+25%).",
      "",
      "# The welfare inspector",
      "- A letter first, then a visit the next morning. More likely with a",
      "  poor name with families or a strong one with the dark market.",
      "- They check the living room, the rooms beside it and the backyard",
      "  (not back rooms or cages): starving, broken or maimed fluffies,",
      "  scars from you, filth, fear of people, crowded or fearful rooms.",
      "- A fine for what they find, and when it's bad, the worst-off",
      "  fluffies are taken to the shelter.",
    ],
  },
  {
    title: "Keys",
    lines: [
      "- WASD or arrow keys: move between areas, carrying what you hold.",
      "  In the house: A/D next room, S backyard, W out the front door",
      "  (hints on the wall; press twice towards a room to buy it).",
      "  In the park they look around instead.",
      "- F: fast forward (1x / 2x / 4x / 8x)",
      "- G: goals        L: breeding records        F1: this help",
      "- T: today (what needs you)        O: household",
      "- M: who's who (the relationship map)    K: accounts",
      "- N: name tags    H: herd markers    B: bed labels",
      "- R: turn the fence piece you're holding",
      "- 0-9: toolbar slots",
      "- J: story debug (what the story book has recorded about the",
      "  fluffy in the magnifying glass, its family, and the whole book)",
      "- Esc: close a window / put down a tool (a tool that misses",
      "  stays in your hand; Esc or its toolbar slot puts it away)",
      "- In this help: up/down arrows pick a topic, left/right turn pages;",
      "  the mouse wheel scrolls the list or turns the page.",
    ],
  },
  {
    title: "Playing on a phone",
    lines: [
      "- Hold your phone sideways, and tap to press buttons and use things.",
      "- Drag to pick something up and carry it; let go to put it down.",
      "  Or tap it, then tap where it should go.",
      "- Press and hold (a ring grows) to train a fluffy, change cage",
      "  modes and feeder settings, and turn things on and off. (The",
      "  rest of the help says \"long-press\" for this, and \"tap\".)",
      "  Hold a tool in the toolbox to put it on the number row (hold a",
      "  slot to empty it).",
      "- Swipe up and down over the chat log, the save list or this help",
      "  to scroll; two fingers zoom the relationship map.",
      "- The round buttons on the right: \u2630 / \u2715 is Esc (close a",
      "  window, put a tool away, pause menu); $ is sell mode (tap a",
      "  fluffy or thing twice to sell it, tap $ again to stop); \u21BB turns",
      "  the fence piece you're holding; \u22EF has the rest (the map,",
      "  accounts, name tags, herds, bed labels, full screen, and faster",
      "  drawing for a slow phone).",
      "- Naming a fluffy: tap its name box and type.",
      "- The magnifying glass, Today and Household open zoomed in, so",
      "  they're easier to read: drag to see the rest.",
      "- \u22EF > Send my save: send your game to another device (on that",
      "  one: Save/Load > Import save from file).",
      "- Full screen: Android goes full screen on your first tap. On an",
      "  iPhone, tap Share, then Add to Home Screen, and open it from",
      "  there.",
    ],
  },
];

let helpOpen = false;
let helpTopic = 0;
let helpTopicScroll = 0; // first topic shown in the list
let helpPage = 0; // page of the current topic's text

const HELP_ROW_H = 28;
const HELP_LINE_H = 22;

function openHelp(topic = helpTopic) {
  helpOpen = true;
  setHelpTopic(topic);
}
function closeHelp() {
  helpOpen = false;
}
function isHelpOpen() {
  return helpOpen;
}
// Open help on a topic by its title ("How a room feels"); used by Hints.js
function openHelpAt(title) {
  const i = HELP_TOPICS.findIndex((t) => t.title === title);
  openHelp(i >= 0 ? i : helpTopic);
}
function setHelpTopic(i) {
  helpTopic = Math.max(0, Math.min(HELP_TOPICS.length - 1, i));
  helpPage = 0;
  // Keep it in view in the list
  const n = helpVisibleTopics();
  if (helpTopic < helpTopicScroll) helpTopicScroll = helpTopic;
  if (helpTopic >= helpTopicScroll + n) helpTopicScroll = helpTopic - n + 1;
  helpTopicScroll = Math.max(0, Math.min(Math.max(0, HELP_TOPICS.length - n), helpTopicScroll));
}

function _helpBox() {
  const w = Math.min(900, width - 40);
  const h = Math.min(620, height - 40);
  return { x: Math.round(width / 2 - w / 2), y: Math.round(height / 2 - h / 2), w, h };
}
// How many topics fit in the list at once
function helpVisibleTopics() {
  const { h } = _helpBox();
  return Math.max(3, Math.floor((h - 62 - 66) / HELP_ROW_H));
}
// How tall a line is drawn
function _helpLineH(line) {
  return line === "" ? 10 : line.startsWith("# ") ? HELP_LINE_H + 4 : HELP_LINE_H;
}
// A topic's lines split into pages that fit (breaking before a heading or
// after a blank line where it can)
function helpPages(topic, maxH) {
  const pages = [];
  let cur = [];
  let used = 0;
  let lastBreak = -1; // index in cur where a new page could start nicely
  for (const line of topic.lines) {
    if (!cur.length && line === "") continue; // no blank line at the top of a page
    const lh = _helpLineH(line);
    if (used + lh > maxH && cur.length) {
      let carry = [];
      const upToBreak = lastBreak > 2 ? cur.slice(0, lastBreak).reduce((sum, l) => sum + _helpLineH(l), 0) : 0;
      if (upToBreak >= maxH * 0.6) {
        carry = cur.slice(lastBreak);
        cur = cur.slice(0, lastBreak);
      }
      while (cur.length && cur[cur.length - 1] === "") cur.pop();
      pages.push(cur);
      cur = carry.filter((l, i) => !(i === 0 && l === ""));
      used = cur.reduce((sum, l) => sum + _helpLineH(l), 0);
      lastBreak = -1;
      if (!cur.length && line === "") continue;
    }
    if (line.startsWith("# ") && cur.length) lastBreak = cur.length;
    else if (line === "" && cur.length) lastBreak = cur.length + 1;
    cur.push(line);
    used += lh;
  }
  while (cur.length && cur[cur.length - 1] === "") cur.pop();
  if (cur.length || !pages.length) pages.push(cur);
  return pages;
}
function helpTextHeight() {
  return _helpBox().h - 100 - 62;
}
function currentHelpPages() {
  return helpPages(HELP_TOPICS[helpTopic], helpTextHeight());
}

function getHelpLayout() {
  const { x, y, w, h } = _helpBox();
  const n = helpVisibleTopics();
  const tabs = HELP_TOPICS.map((t, i) => {
    const row = i - helpTopicScroll;
    if (row < 0 || row >= n) return null;
    return { x: x + 20, y: y + 62 + row * HELP_ROW_H, w: 200, h: HELP_ROW_H - 4 };
  });
  const listBottom = y + 62 + n * HELP_ROW_H;
  const more = HELP_TOPICS.length > n;
  const tx = x + 250;
  return {
    x,
    y,
    w,
    h,
    tabs,
    list: { x: x + 20, y: y + 62, w: 200, h: n * HELP_ROW_H },
    up: more ? { x: x + 20, y: listBottom + 2, w: 96, h: 28 } : null,
    down: more ? { x: x + 124, y: listBottom + 2, w: 96, h: 28 } : null,
    text: { x: tx, y: y + 80, w: w - 270, h: helpTextHeight() + 20 },
    prev: { x: tx, y: y + h - 54, w: 110, h: 36 },
    next: { x: tx + 250, y: y + h - 54, w: 110, h: 36 },
    hints: { x: x + w - 170, y: y + 18, w: 150, h: 30 },
    close: { x: x + w - 150, y: y + h - 54, w: 130, h: 36 },
  };
}

function _helpButton(r, label, opts = {}) {
  if (!r || typeof drawGlassButton !== "function") return;
  drawGlassButton(r.x, r.y, r.w, r.h, label, { fontSize: 15, borderRadius: 9, ...opts });
}

function drawHelp(c) {
  if (!helpOpen) return;
  if (typeof ctx !== "undefined" && c !== ctx) return;
  const L = getHelpLayout();
  c.save();
  // Dimmed background and the panel (UIPanels.js)
  drawScreenPanel(c, L, { theme: "pink", dim: 0.5 });
  c.textBaseline = "alphabetic";
  c.textAlign = "left";
  c.fillStyle = "#ffd6f0";
  c.font = "bold 24px Arial";
  c.fillText("How it works", L.x + 24, L.y + 42);

  // Topics (the list scrolls when they don't all fit)
  L.tabs.forEach((t, i) => {
    if (!t) return;
    const on = i === helpTopic;
    c.fillStyle = on ? "rgba(255, 170, 220, 0.25)" : "rgba(255,255,255,0.05)";
    fillRoundRect(c, t.x, t.y, t.w, t.h, 8);
    c.fillStyle = on ? "white" : "rgba(255,255,255,0.75)";
    c.font = on ? "bold 15px Arial" : "15px Arial";
    c.fillText(HELP_TOPICS[i].title, t.x + 12, t.y + 18);
  });
  if (L.up) {
    const n = helpVisibleTopics();
    _helpButton(L.up, "\u25B2", { disabled: helpTopicScroll <= 0 });
    _helpButton(L.down, "\u25BC", { disabled: helpTopicScroll >= HELP_TOPICS.length - n });
  }

  // Text, a page at a time
  const topic = HELP_TOPICS[helpTopic];
  const pages = currentHelpPages();
  const page = Math.max(0, Math.min(pages.length - 1, helpPage));
  const tx = L.text.x;
  let y = L.y + 100;
  c.font = "bold 20px Arial";
  c.fillStyle = "#ffd6f0";
  c.fillText(topic.title, tx, L.y + 70);
  for (const line of pages[page]) {
    if (line === "") {
      y += 10;
      continue;
    }
    if (line.startsWith("# ")) {
      y += 4;
      c.font = "bold 15px Arial";
      c.fillStyle = "#f7d774";
      c.fillText(line.slice(2), tx, y);
    } else {
      c.font = "15px Arial";
      c.fillStyle = "rgba(255,255,255,0.9)";
      c.fillText(line, tx, y);
    }
    y += HELP_LINE_H;
  }
  if (pages.length > 1) {
    _helpButton(L.prev, "\u25C0 Back", { disabled: page === 0 });
    _helpButton(L.next, "More \u25B6", { disabled: page === pages.length - 1 });
    c.font = "14px Arial";
    c.fillStyle = "rgba(255,255,255,0.7)";
    c.textAlign = "center";
    c.fillText(`Page ${page + 1} of ${pages.length}`, (L.prev.x + L.prev.w + L.next.x) / 2, L.prev.y + 23);
    c.textAlign = "left";
  }

  // First-time hints on or off (Hints.js)
  if (typeof hintsOn === "function") _helpButton(L.hints, hintsOn() ? "Hints: on" : "Hints: off", { fontSize: 14 });
  _helpButton(L.close, "Close", { fontSize: 16, borderRadius: 10 });
  c.restore();
}

function helpNextPage(d) {
  const pages = currentHelpPages();
  helpPage = Math.max(0, Math.min(pages.length - 1, helpPage + d));
}
function helpScrollTopics(d) {
  const n = helpVisibleTopics();
  helpTopicScroll = Math.max(0, Math.min(Math.max(0, HELP_TOPICS.length - n), helpTopicScroll + d));
}

// Mouse down (screen positions); swallows clicks while open
function handleHelpClick() {
  if (!helpOpen) return false;
  const L = getHelpLayout();
  const hit = (r) => r && isPointInRect(mouse.x, mouse.y, r.x, r.y, r.w, r.h);
  if (hit(L.close) || !isPointInRect(mouse.x, mouse.y, L.x, L.y, L.w, L.h)) {
    closeHelp();
    return true;
  }
  if (hit(L.hints) && typeof setHintsOn === "function") {
    setHintsOn(!hintsOn());
    return true;
  }
  if (hit(L.up)) return helpScrollTopics(-3), true;
  if (hit(L.down)) return helpScrollTopics(3), true;
  if (currentHelpPages().length > 1) {
    if (hit(L.prev)) return helpNextPage(-1), true;
    if (hit(L.next)) return helpNextPage(1), true;
  }
  L.tabs.forEach((t, i) => {
    if (hit(t)) setHelpTopic(i);
  });
  return true;
}

// Mouse wheel (globals.js): over the list it scrolls the topics, over the
// text it turns the page
function handleHelpScroll(dy) {
  if (!helpOpen || !dy) return false;
  const L = getHelpLayout();
  const d = dy > 0 ? 1 : -1;
  if (isPointInRect(mouse.x, mouse.y, L.list.x, L.list.y - 10, L.list.w, L.list.h + 50)) helpScrollTopics(d);
  else helpNextPage(d);
  return true;
}

// Keys while it's open (script.js): up/down pick a topic, left/right turn pages
function handleHelpKey(code) {
  if (!helpOpen) return false;
  if (code === "ArrowUp") setHelpTopic(helpTopic - 1);
  else if (code === "ArrowDown") setHelpTopic(helpTopic + 1);
  else if (code === "ArrowLeft" || code === "PageUp") helpNextPage(-1);
  else if (code === "ArrowRight" || code === "PageDown") helpNextPage(1);
  else return false;
  return true;
}

// Pop-up screen list (Screens.js)
registerScreen({
  name: "help",
  layer: 21,
  isOpen: () => helpOpen,
  close: () => closeHelp(),
  draw: (c) => drawHelp(c),
  click: () => handleHelpClick(),
  reset: () => {
    helpOpen = false;
    helpTopic = 0;
    helpTopicScroll = 0;
    helpPage = 0;
  },
});
