const images = {};
const imageSources = {
  bmac: "assets/bmac.png",
  head: "assets/horse_head.png",
  sbs_double_chin: "assets/sbs_double_chin.png",
  torso: "assets/horse_torso.png",
  tail: "assets/horse_tail.png",
  leg: "assets/horse_leg.png",
  grinder: "assets/grinder.png",
  grinder_blade: "assets/grinder_blade.png",
  mane_0: "assets/horse_mane_0.png",
  mane_1: "assets/horse_mane_1.png",
  mane_2: "assets/horse_mane_2.png",
  mane_3: "assets/horse_mane_3.png",
  mane_4: "assets/horse_mane_4.png",
  mane_5: "assets/horse_mane_5.png",
  ear: "assets/horse_ear.png",
  cheek: "assets/horse_cheek.png",
  cheek_sbs: "assets/horse_cheek_sbs.png",
  puffed_cheek: "assets/horse_puffed_cheek.png",
  eye: "assets/horse_eye.png",
  pupil: "assets/horse_pupil.png",
  bowl: "assets/bowl.png",
  kibble_bowl: "assets/kibble_bowl.png",
  kibble_half_bowl: "assets/kibble_half_bowl.png",
  trough: "assets/trough.png",
  kibble_half_trough: "assets/kibble_half_trough.png",
  kibble_trough: "assets/kibble_trough.png",
  soylent_brown_bowl: "assets/soylent_brown_bowl.png",
  soylent_brown_trough: "assets/soylent_brown_trough.png",
  rat_poison_bowl: "assets/rat_poison_bowl.png",
  rat_poison_trough: "assets/rat_poison_trough.png",
  castration_band: "assets/castration_band.png",
  sketties_half_trough: "assets/sketties_half_trough.png",
  sketties_trough: "assets/sketties_trough.png",
  wing: "assets/wing_1.png",
  horn: "assets/horn.png",
  eye_happy: "assets/eye_happy.png",
  eye_pained: "assets/eye_pained.png",
  eye_sad: "assets/eye_sad.png",
  eye_angry: "assets/eye_angry.png",
  ball_normal: "assets/ball_normal.png",
  ball_jellenheimer: "assets/ball_jellenheimer.png",
  block_e: "assets/block_e.png",
  block_p: "assets/block_p.png",
  block_t: "assets/block_t.png",
  block_n: "assets/block_n.png",
  horse_udders: "assets/horse_udders.png",
  golden_statue: "assets/golden_statue.png",
  fluff_tv_off: "assets/fluff_tv_off.png",
  fluff_tv_play_time_1: "assets/fluff_tv_playtime_1.png",
  fluff_tv_play_time_2: "assets/fluff_tv_playtime_2.png",
  fluff_tv_babbehs_1: "assets/fluff_tv_babbehs_1.png",
  fluff_tv_heavy_metal_1: "assets/fluff_tv_heavy_metal_1.png",
  fluff_tv_heavy_metal_2: "assets/fluff_tv_heavy_metal_2.png",
  fluff_tv_torture_1: "assets/fluff_tv_torture_1.png",
  fluff_tv_torture_2: "assets/fluff_tv_torture_2.png",
  fluff_tv_alicorn_1: "assets/fluff_tv_alicorn_1.png",
  fluff_tv_poopies_1: "assets/fluff_tv_poopies_1.png",
  bed: "assets/bed.png",
  bed_wood: "assets/bed_wood.png",
  cardboard_box: "assets/cardboard_box.png",
  bed_fluff_back: "assets/bed_fluff_back.png",
  bed_fluff_middle: "assets/bed_fluff_middle.png",
  bed_fluff_front: "assets/bed_fluff_front.png",
  baby_feeder: "assets/baby_feeder.png",
  formula_half_baby_feeder: "assets/formula_half_baby_feeder.png",
  formula_baby_feeder: "assets/formula_baby_feeder.png",
  mega_baby_feeder: "assets/mega_baby_feeder.png",
  mega_half_formula_baby_feeder: "assets/mega_half_formula_baby_feeder.png",
  mega_formula_baby_feeder: "assets/mega_formula_baby_feeder.png",
  sketties_bowl: "assets/sketties_bowl.png",
  sketties_half_bowl: "assets/sketties_half_bowl.png",
  food_bag: "assets/food_bag.png",
  sorry_stick: "assets/sorry_stick.png",
  spray_bottle: "assets/spray_bottle.png",
  sponge: "assets/sponge.png",
  knife: "assets/knife.png",
  operating_table: "assets/operating_table.png",
  scalpel: "assets/scalpel.png",
  thumbtack: "assets/thumbtack.png",
  accessory_fez: "assets/fez.png",
  accessory_tophat: "assets/tophat.png",
  accessory_scarf: "assets/scarf.png",
  accessory_blindfold: "assets/blindfold.png",
  accessory_glasses: "assets/eyeglasses.png",
  accessory_sunglasses: "assets/sunglasses.png",
  accessory_wingjacket: "assets/wingjacket.png",
  accessory_mouthgag: "assets/mouthgag.png",
  accessory_bow: "assets/bow.png",
  accessory_kippah: "assets/yarmulke.png",
  accessory_duncehat: "assets/duncehat.png",
  accessory_crown: "assets/crown.png",
  accessory_partyhat: "assets/partyhat.png",
  magnifying_glass: "assets/magnifying_glass.png",
  cage: "assets/cage.png",
  enclosure: "assets/enclosure.png",
  tail_0: "assets/horse_tail_0.png",
  tail_1: "assets/horse_tail_1.png",
  litterbox: "assets/litterbox.png",
  litterbox_partially_full: "assets/litterbox_partially_full.png",
  litterbox_full: "assets/litterbox_full.png",
  brush: "assets/brush.png",
  special_lumps: "assets/special_lumps.png",
  immobilization_board: "assets/immobilization_board.png",
  immobilization_board_in_use: "assets/immobilization_board_in_use.png",
  sprinkler_on: "assets/sprinkler_on.png",
  sprinkler_off: "assets/sprinkler_off.png",
  mouth_happy: "assets/mouth_happy.png",
  mouth_neutral: "assets/mouth_neutral.png",
  mouth_sad: "assets/mouth_sad.png",
  mouth_shock: "assets/mouth_shock.png",
  suture_kit: "assets/suture_kit.png",
  trash_bag_empty: "assets/trash_bag_empty.png",
  trash_bag_partially_full: "assets/trash_bag_partially_full.png",
  trash_bag_full: "assets/trash_bag_full.png",
  iv_stand: "assets/iv_stand.png",
  iv_bag: "assets/iv_bag.png",
  syringe: "assets/syringe.png",
  cattle_prod: "assets/cattle_prod.png",
  door: "assets/door.png",
  texture_carpet: "assets/texture_carpet.png",
  texture_concrete: "assets/texture_concrete.png",
  texture_grass: "assets/texture_grass.png",
  grass: "assets/grass.png",
  litterpal_box: "assets/litterpal_box.png",
  litterpal_box_kit: "assets/litterpal_box_kit.png",
  lbb_outtake_empty: "assets/lbb_outtake_empty.png",
  lbb_outtake_full: "assets/lbb_outtake_full.png",
  lbb_outtake_used: "assets/lbb_outtake_used.png",
  dream_ball: "assets/dream/dream_ball.png",
  dream_block: "assets/dream/dream_block.png",
  dream_man: "assets/dream/dream_man.png",
  dream_sketties: "assets/dream/dream_sketties.png",
  dream_sun: "assets/dream/dream_sun.png",
  title_1: "assets/title_1.png",
  title_2: "assets/title_2.png",
  fence_post: "assets/fence_post.png",
  crummy_fence_post: "assets/crummy_fence_post.png",
  reinforced_fence_post: "assets/reinforced_fence_post.png",
  crummy_fence_post_damaged: "assets/crummy_fence_post_damaged.png",
  fence_post_damaged: "assets/fence_post_damaged.png",
  reinforced_fence_post_gate: "assets/reinforced_fence_post_gate.png",
  foal_vendor: "assets/foal_vendor.png",
  foal_in_a_can: "assets/foal_in_a_can.png",
  day_care_desk: "assets/day_care_desk.png",
  car_1: "assets/car_1.png",
  car_2: "assets/car_2.png",
  tire_1: "assets/tire_1.png",
  tire_2: "assets/tire_2.png",
  throw_tool_held: "assets/throw_tool_held.png",
  throw_tool_unheld: "assets/throw_tool_unheld.png",
};

const totalImages = Object.keys(imageSources).length;
let imagesLoadedCount = 0;

function loadImages(onAllLoaded) {
  for (const [key, src] of Object.entries(imageSources)) {
    images[key] = new Image();
    images[key].src = src;
    images[key].onload = () => {
      imagesLoadedCount++;
      if (imagesLoadedCount === totalImages) {
        if (onAllLoaded) onAllLoaded();
      }
    };
    images[key].onerror = () => {
      console.error(`Failed to load image: ${src}`);
    };
  }
}
